export const USERS_COLLECTION = "users"
export const TRAVELLING_TABLE = "future_travelling"
export const defaultBackground = "/static/images/logo-1.jpg"
export const GET_NOTIFICATION_METHOD = "getNotifications"
export const GET_PREVIEW_MESSAGES_METHOD = "getPrviewMessages"
export const GET_ALL_MESSAGES_BY_USER_METHOD = "getAllMessagesByUser"
export const GET_PROFILE_METHOD = "getProfile"
export const UPDATE_PROFILE_METHOD = "SAVE_PROFILE"
export const SEND_MESSAGE_METHOD = "SEND_MESSAGE_METHOD"
export const GET_PROFILES_METHOD = "GET_PROFILES"
export const GET_CITY_DATA = "GET_CITY_DATA"
export const POST_MESSAGE = "POST_MESSAGE"
export const POST_COMMENT = "POST_COMMENT"
export const GET_MESSAGES = "GET_MESSAGES"
export const GET_POST_COMMENTS = "GET_POST_COMMENTS"
export const CityPostsTable = "city_posts"
export const CITY_COMMENTS_TABLE = "city_comments"
export const START_FOLLOW = "START_FOLLOW"
export const STOP_FOLLOW = "STOP_FOLLOW"
export const MAX_POSTS_PER_PAGE = 2
export const EMPTY_PROFILE_PICTURE =
  "https://akadem.org.il/wp-content/uploads/2020/05/blank-profile-picture-973460_640.png"

export const SEND_MESSAGE_API = "/api/messagesApi"

export const ProfileParams = { name: 1, picture: 1, cityId: 1, userId: 1 }
export const GET_FOLLOWING = "GET_FOLLOWING"
export const CITY = "CITY"
export const FOLLOW = "FOLLOW"
export const POST_NEW_ITINERARY = "POST_NEW_ITINERARY"
export const GET_CITY_ITINERARIES = "GET_CITY_ITINERARIES"
export const GET_USER_ITINERARIES = "GET_USER_ITINERARIES"